add rfc3986-compliance
Mindera/Alicerce pull request #222
Opened 2020-10-21 16:25 UTC by JOCuendet

### Checklist
- [x] I've rebased my changes on top of `master`
- [x] I've built and run the project to see all new and existing tests pass
- [x] I've followed the [Mindera swift style guide](https://github.com/Mindera/swift-style-guide)
- [x] I've read the [Contribution Guidelines](https://github.com/Mindera/Alicerce/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
The current implementation did not account for [RFC-3986](https://tools.ietf.org/html/rfc3986#section-6.2.2.1), and by doing so if the user entered an URL with a capital letters in the scheme or the host the match would fail.
By complying to the norm, this behaviour is now accounted for, and the issue is fixed.

### Description
Forcing the scheme and host from the user's input URL to be lowercased before parsing them to the match method.
Changed a UnitTest to accommodate to the base code changes.
Tested applying the code to a working project and running the app on a physical device to debug the deep links and universal links

2020-10-21 16:38 UTC, filipe-lemos approved these changes
Nice fix! 🎉 Perhaps add a couple of unit tests to `Route+TrieRouter_RouteTests` that check for case-insensitive matches.

2020-10-21 21:06 UTC, ricardomsm approved these changes

2020-10-22 08:34 UTC, literallysofia approved these changes

2020-10-22 08:36 UTC, nbarreto6 approved these changes

2020-10-22 08:46 UTC, nqtavares approved these changes

2020-10-22 08:49 UTC, p4checo requested changes
Nice improvement! 💪 

Some suggestions:
- please add some new unit tests to check new behavior 🤓 
- the PR title (and final commit) could still be improved: perhaps "Make route scheme and host checks case insensitive"? 💅

2020-10-22 08:49 UTC, p4checo commented on Sources/DeepLinking/Route+TrieRouter.swift
>              // use a wildcard for empty schemes/hosts, to match any scheme/host
perhaps we could add a comment that host and scheme comparison should be case insensitive because of RFC3986 (same case below)

2020-10-22 11:51 UTC, p4checo approved these changes
Nice one! Just some minor tweaks left IMO 👍

2020-10-22 11:51 UTC, p4checo commented on Tests/AlicerceTests/DeepLinking/Route+TrieRouter_RouteTests.swift
> +    func testRoute_WithCaseInsensetiveScheme_shouldSucceed() {
typo in "Insensetive", and "Should" should start with uppercase

also, perhaps:
`testRoute_WithCaseInsensitiveMatchingScheme_ShouldSucceed()`
`testRoute_WithCaseInsensitiveMatchingHost_ShouldSucceed()`

And maybe use some weird variations like `HttP` and `HoSt`, to make it clearer? (ie. not just CAPS vs caps)

2020-10-22 13:57 UTC, IvoPintodaSilva approved these changes

2020-10-22 16:24 UTC, merged